Update ots-generate-password
Working script

diff --git a/ots-generate-password b/ots-generate-password
--- a/ots-generate-password
+++ b/ots-generate-password
@@ -3,54 +3,60 @@
 # This script will create password secrets for the given Usernames.
 # The password secrets will be generated by default on onetimesecrect.com, but you can change this
 # to your own ots instance.
-#	
-#	created		- Ullrich Weichert
-#	edit 		- 
-#	last edit	- 24.06.2021
-#	version		- 0.0
-VERSION="0.0"
-RELEASE="Aufmerksame Apostel analysieren afrikanische Apfelernten."
-#	
+# You need CURL and JQ to run this script probably.
 
-#### check if the script is already running
-
-pname="$(echo $0|sed 's@.*/@@')"
-semname="${pname}.pid"
-semfile="/tmp/${semname}"
-if [ -f "${semfile}" ]; then
-        pid="$(cat "${semfile}")"
-        if [ -f "/proc/${pid}/stat" ]; then
-                id="$(cat /proc/$$/stat|awk '{print $2}')"
-                if [ -n "$(grep -P "\Q${id}\E" "/proc/${pid}/stat")" ]; then
-                        echo "$(date): $pname is already running!"
-                        exit 1
-                fi
-        fi
-fi
-echo $$ > "${semfile}"
-
-#url=$(curl -s -d secret=${sec} -d "ttl=1209600" -u "ullrich@weichert.it:09d60525cafe97276d3a84129867dabe317a0c25" https://onetimesecret.com/api/v1/share | jq .secret_key | sed -e 's/^"//' -e 's/"$//'); echo "https://onetimesecret.com/secret/${url}"
+BUILDNUMBER="21082501"
+VERSION="1.0.${BUILDNUMBER}"
+RELEASE="Cindy caught creepy caterpillars and cool crickets close to the carnations and camellias in Claudia's cottage."
 
 #### Variables
 
 OTSINSTANCE="onetimesecret.com"
 APIPATH="/api/v1/"
-APITOKEN=""
-APIUSER=""
+APITOKEN="09d60525cafe97276d3a84129867dabe317a0c25"
+APIUSER="ullrich@weichert.it"
 RECIPIENT=""
 LIST=""
+USERNAME=""
+PASSWORD=""
 PWLENGTH=20
 TTL=14
-VERBOSE_OUT=false
-BATCH_OUT=false
+
+VERBOSEOUT=""
+BATCHOUT=""
 WUMMMMS=false
 
 CURL=$(type -p curl)
 AWK=$(type -p awk)
 SED=$(type -p sed)
+JQ=$(type -p jq)
 
-url="https://${OTSINSTANCE}${APIPATH}"
-ttlinseconds=$(( ${TTL} * 24 * 60 * 60 ))
+FULLOTSURL="https://${OTSINSTANCE}${APIPATH}"
+
+TTLINSECONDS=$(( ${TTL} * 24 * 60 * 60 ))
+
+#### Check dependencies
+# check for mandatory tools
+if [[ -z ${SED} ]];
+	then
+		echo -e "\033[31mERROR:\e[0m sed not found, but is needed. Exit!\n"
+		exit 1
+fi
+if [[ -z ${CURL} ]];
+	then
+		echo -e "\033[31mERROR:\e[0m cURL not found, but is needed. Exit!\n"
+		exit 1
+fi
+if [[ -z ${AWK} ]];
+	then
+		echo -e "\033[31mERROR:\e[0m awk not found, but is needed. Exit!\n"
+		exit 1
+fi
+if [[ -z ${JQ} ]];
+	then
+		echo -e "\033[31mERROR:\e[0m jq not found, but is needed. Exit!\n"
+		exit 1
+fi
 
 #### Functions
 
@@ -80,80 +86,171 @@ usage ()
 {
 	echo -e "\n\n$(basename $0)"
 	echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-	echo -e "This script is for generating passwords and creating onetime links for password exchange."
-	echo -e "You can define a password by yourself and hand it over to this script."
+	echo -e "This script is for generating passwords and creating onetime links for a password exchange."
+	echo -e "with your users. You can define a password by yourself and hand it over to this script."
+	echo -e "It is also possible to hand over a list with parameter -f,"
+	echo -e "but please use the suggested format for the list."
+	echo -e ""
+	echo -e "Dependencies:"
+	echo -e "You need CURL and JQ to run this script! Please install these little tools before"
+	echo -e "runing this script."
 	echo -e ""
 	echo -e "Usage : $(basename $0) "
 	echo -e ""
 	echo -e "\t-W\t\tUse this script with power!"
-	echo -e "\t-V\t\tMore Output as usual."
-	echo -e "\t-v\t\tTell you the version"
-	echo -e "\t-b\t\tFor batch processing without any output - exept returncode"
-	echo -e "\t\t0\tOk!"
-	echo -e "\t\t1\tnOk!"
+	echo -e "\t-V\t\tMore Output as usual - for debugging."
+	echo -e "\t-L\t\tChose the amount of characters in the password.\n\t\t\t\e[92mDefault: 20\e[0m"
+	echo -e "\t-v\t\tVersion and Release of this script."
+	echo -e "\t-R\t\tSpecify a recipient. Value needs to be an valid email address.\n\t\t\tThe recipient will be set in ots."
+	echo -e "\t-U\t\tSpecify a Username. The Username will also be set in OTS Secret."
+	echo -e "\t-f\t\tFile with usernames and passwords. The Username is mandatory.\n\t\t\t\tPlease use the following format for the file:\n\t\t\t\tFirst column Username and second column password.\n\t\t\t\tPlease use a TAB as delimeter.\n\t\t\t\t\e[31mPlease use no headerrow\e[0m!\n"
+	echo -e "\t-P\t\tSpecify a password, that will be send via ots link."
+	echo -e "\t-t\t\tOnly check if the ots instance is fine and reachable."
+	echo -e ""
+	echo -e "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
 	echo -e ""
 	echo -e "\n\e[92mVersion: $VERSION"
-	echo -e "Release: $RELEASE\e[0m"
+	echo -e "Release: $RELEASE"
+	echo -e "Copyright by \e[0m\e[1;44;214mCLOUDSUPPLIES\e[0;0;92m - Created by Ulli\n\n\e[0m"
+	echo -e "Opensource - Script for batchusage only directly by CLOUDSUPPLIES."
 	exit
+}
+
+checking_lifestate ()
+{
+	## Check if OTS instance is reachable and healthy
+	echo -e "\n##########################################################\n"
+	echo -e "Checking if ots instance is reachable...\n"
+	otsreach=$(ping -c1 ${OTSINSTANCE} > /dev/null 2>&1;)
+	if [[ ${otsreach} -ne 0 ]];
+		then 
+			echo -e "OTS instance is\t[\e[31mnot reachable\e[0m]\n"
+			echo -e "Leaving script - check the ots instance and configuration"
+			echo -e "\n##########################################################\n"
+			exit 1;
+		else 
+			echo -e "OTS instance is\t[\e[92mreachable\e[0m]\n"
+	fi
+
+	echo -e "Checking if ots instance is healthy...\n"
+	otsstatus=$(curl -s ${FULLOTSURL}status | jq .status | sed -e 's/^"//' -e 's/"$//')
+	if [[ ${otsstatus} -eq "nominal" ]]; 
+		then 
+			echo -e "OTS instance is\t[\e[92mhealthy\e[0m]\n"
+		else 
+			echo -e "OTS instance is\t[\e[31mnot healthy\e[0m]\n"
+			echo -e "Leaving script - check the ots instance and/or configuration"
+			echo -e "\n##########################################################\n"
+			exit 1;
+	fi	
+	echo -e "Everything seems nice and sweet!"
+	echo -e "\n##########################################################\n"
 }
 
 generate_password ()
 {
-	openssl rand -base64 ${1}
+	tr -dc 'A-Za-z0-9!"<>'\''()*,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c${1}; echo
 }
 
 generate_ots_link ()
 {
-	echo -e "Generating passwords links..."
-	
+	if [[ ! -z ${2} ]];
+		then
+			pwonetimelink=$(curl -s -d "secret=${1}" -d "ttl=${TTLINSECONDS}" -d "recipient=${2}" -u "${APIUSER}:${APITOKEN}" ${FULLOTSURL}share | jq .secret_key | sed -e 's/^"//' -e 's/"$//';)
+			echo "https://${OTSINSTANCE}/secret/${pwonetimelink}"
+		else
+			pwonetimelink=$(curl -s -d "secret=${1}" -d "ttl=${TTLINSECONDS}" -u "${APIUSER}:${APITOKEN}" ${FULLOTSURL}share | jq .secret_key | sed -e 's/^"//' -e 's/"$//';)
+			echo "https://${OTSINSTANCE}/secret/${pwonetimelink}"
+	fi
+	echo -e ""
 }
 
-#### Optionen
-while getopts VbWvh opt 2>/dev/null
+#### Options
+while getopts VbWL:f:vU:P:R:th opt 2>/dev/null
 do
    case $opt in
-	V)	VERBOSE_OUT=true;;
-	b)	BATCH_OUT=true;;
-	W)	WUMMMMS=true;;
+	V)	VERBOSEOUT=true;;
+	b)	BATCHOUT=true;;
+	W)	wumms;;
+	L)	
+		if [[ ${OPTARG} -le "8" ]]; 
+			then echo -e "\n\e[31mYour chosen passwordlength of ${OPTARG} character is not so much secure!\n\e[0mWe suggest 12 character and more.\n\nDefault of this script is 20 chars.\n\n"
+			PWLENGTH=${OPTARG}
+		else
+			PWLENGTH=${OPTARG}
+		fi
+		;;
+	f)	LIST=${OPTARG};;
 	v) 	echo -e "\n$(basename $0) - Version: ${VERSION}"
 		echo -e "${RELEASE}"
 		exit;;
-    \?) echo -e "\n($0): \033[31mERROR:\e[0m - A wild error occurs - please check the chosen options."
-        exit;;
+	U)
+		USERNAME=${OPTARG};;
+	P)
+		PASSWORD=${OPTARG};;
+	R)
+		RECIPIENT=${OPTARG};;
+	t)
+		checking_lifestate
+		exit;;
+    \?) echo -e "\n($0): \033[31mERROR:\e[0m - A wild error occurs in the gras - get a pokeball... and check the chosen options."
+        exit 1;;
 	h|*)usage
 		exit;;
    esac
 done
 
-
-#### Check dependencies
-# check for mandatory tools
-if [[ -z ${SED} ]];
-	then
-		echo -e "\033[31mERROR:\e[0m sed wurde nicht gefunden, wird aber gebraucht. Programmabbruch!\n"
-		exit
-fi
-if [[ -z ${CURL} ]];
-	then
-		echo -e "\033[31mERROR:\e[0m cURL wurde nicht gefunden, wird aber gebraucht. Programmabbruch!\n"
-		exit
-fi
-if [[ -z ${AWK} ]];
-	then
-		echo -e "\033[31mERROR:\e[0m awk wurde nicht gefunden, wird aber gebraucht. Programmabbruch!\n"
-		exit
-fi
-
-# check for mandatory options
-#if [[ -z ${COMPARE_HASH} ]];
-#	then
-#		echo -e "\033[31mERROR:\e[0m Es wurde keine md5sum übergeben. Programmabbruch!\n"
-#		usage
-#		exit
-#fi
-
 #### maincode
 
-password=$(generate_password ${PWLENGTH})
+if [[ ! -z ${VERBOSEOUT} ]];
+then
+	checking_lifestate
+fi
 
-echo -e "Hier kommt Ihr Passwort:\t$password"
+if [[ -z ${LIST} ]];
+	then
+		if [[ -z ${PASSWORD} ]];
+			then
+				echo -e "Generating a strong password for you...\n"
+				PASSWORD=$(generate_password ${PWLENGTH})
+		fi
+fi
+
+if [[ ! -z ${VERBOSEOUT} ]];
+	then
+		## For debugging
+		echo -e "This is the password:\n\t${PASSWORD}\n"
+fi
+
+if [[ ! -z ${LIST} ]]
+	then
+		USERNAMES=($(awk -F'\t' '{ print $1 }' ${LIST}))
+		PASSWORDS=($(awk -F'\t' '{ print $2 }' ${LIST}))
+		counter=0
+		for user in "${USERNAMES[@]}" 
+		do
+			echo -e "Generating ots links username [\e[33m${user}\e[0m]."
+			generate_ots_link ${user} ${RECIPIENT}
+			if [[ ! -z ${PASSWORDS} ]];
+				then
+					echo -e "Generating ots links for password (${PASSWORDS[${counter}]}) to user [\e[33m${user}\e[0m]."
+					generate_ots_link ${PASSWORDS[${counter}]} ${RECIPIENT}
+				else		
+					PASSWORD=$(generate_password ${PWLENGTH})
+					echo -e "Generating ots links for password (${PASSWORD}) to user [\e[33m${user}\e[0m]." 
+					generate_ots_link ${PASSWORD} ${RECIPIENT}
+			fi
+			let counter=$counter+1
+		done
+	else
+		if [[ ! -z ${USERNAME} ]]
+			then
+				echo -e "Generating ots username link..."
+				generate_ots_link ${USERNAME} ${RECIPIENT}
+				echo -e "Generating ots password link..."
+				generate_ots_link ${PASSWORD} ${RECIPIENT}
+			else 
+				echo -e "Generating ots password link..."
+				generate_ots_link ${PASSWORD} ${RECIPIENT}
+		fi
+fi
